name: Build Android for Google Play

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  android_production_build:
    name: Build Android production AAB
    type: build
    params:
      platform: android
      profile: production
